apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: {{ .Values.nginx.namespace }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
  selector:
    app: nginx-proxy
