nginx:
  name: nginx-proxy
  namespace: nginx
  upstreamUrl: "wpapp.wpapp.svc.cluster.local"
  upstreamPort: 80
  replicas: 3
  image:
    repository: vicky04/nginx
    tag: v1
  service:
    type: NodePort
    port: 80

