nginx:
  name: nginx-dep
  namespace: nginx1
  upstreamUrl: "my-upstream-url"
  upstreamPort: 8080
  replicas: 3  # More replicas for production
  image:
    repository: vicky04/nginx
    tag: v1
  service:
    type: LoadBalancer
    port: 80
