wp:
  name: wpapp
  labels:
    app: wp
    env: dev
    stack: wordpress
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 2
  configmap:
    ## KEY: "value"
    APP_ENV: "dev"
    WORDPRESS_DB_HOST: "wp-database.wpdb.svc.cluster.local"
    WORDPRESS_DB_NAME: "C0927938"
    WORDPRESS_DB_USER: "3324_user"
  containerPorts:
      http: 80
