nginx:
  namespace: nginx1
  upstreamUrl: "my-upstream-url"
  upstreamPort: 8080
  replicas: 1
  image:
    repository: vicky04/nginx
    tag: v1
  service:
    type: ClusterIP  # Default service type, can be overridden for different environments
    port: 80
